# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AccountFile\Desk\BaiYe\Demo\Demo\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 643)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 40, 193, 362))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lENumber = QtWidgets.QLineEdit(self.groupBox)
        self.lENumber.setText("")
        self.lENumber.setObjectName("lENumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lENumber)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cBSex = QtWidgets.QComboBox(self.groupBox)
        self.cBSex.setObjectName("cBSex")
        self.cBSex.addItem("")
        self.cBSex.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cBSex)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lEAge = QtWidgets.QLineEdit(self.groupBox)
        self.lEAge.setObjectName("lEAge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lEAge)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lEParam1 = QtWidgets.QLineEdit(self.groupBox)
        self.lEParam1.setObjectName("lEParam1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lEParam1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lEParam2 = QtWidgets.QLineEdit(self.groupBox)
        self.lEParam2.setObjectName("lEParam2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lEParam2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lEParam3 = QtWidgets.QLineEdit(self.groupBox)
        self.lEParam3.setObjectName("lEParam3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lEParam3)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lEInvestTime = QtWidgets.QLineEdit(self.groupBox)
        self.lEInvestTime.setObjectName("lEInvestTime")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lEInvestTime)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cBParam4 = QtWidgets.QComboBox(self.groupBox)
        self.cBParam4.setObjectName("cBParam4")
        self.cBParam4.addItem("")
        self.cBParam4.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cBParam4)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lEStock = QtWidgets.QLineEdit(self.groupBox)
        self.lEStock.setObjectName("lEStock")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lEStock)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lEParam5 = QtWidgets.QLineEdit(self.groupBox)
        self.lEParam5.setObjectName("lEParam5")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lEParam5)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lEParam6 = QtWidgets.QLineEdit(self.groupBox)
        self.lEParam6.setObjectName("lEParam6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lEParam6)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(50, 540, 252, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lEResult = QtWidgets.QLineEdit(self.widget)
        self.lEResult.setObjectName("lEResult")
        self.horizontalLayout.addWidget(self.lEResult)
        self.btnPredict = QtWidgets.QPushButton(self.widget)
        self.btnPredict.setObjectName("btnPredict")
        self.horizontalLayout.addWidget(self.btnPredict)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "参数输入"))
        self.label_12.setText(_translate("MainWindow", "编号"))
        self.label_2.setText(_translate("MainWindow", "性别"))
        self.cBSex.setItemText(0, _translate("MainWindow", "male"))
        self.cBSex.setItemText(1, _translate("MainWindow", "female"))
        self.label_3.setText(_translate("MainWindow", "年龄"))
        self.label_4.setText(_translate("MainWindow", "参数1"))
        self.label_5.setText(_translate("MainWindow", "参数2"))
        self.label_6.setText(_translate("MainWindow", "参数3"))
        self.label_7.setText(_translate("MainWindow", "入股时间"))
        self.label_8.setText(_translate("MainWindow", "参数4"))
        self.cBParam4.setItemText(0, _translate("MainWindow", "Yes"))
        self.cBParam4.setItemText(1, _translate("MainWindow", "No"))
        self.label_9.setText(_translate("MainWindow", "股票"))
        self.label_10.setText(_translate("MainWindow", "参数5"))
        self.label_11.setText(_translate("MainWindow", "参数6"))
        self.label.setText(_translate("MainWindow", "预测结果"))
        self.btnPredict.setText(_translate("MainWindow", "预测"))

